stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: IMG_fiware-mongodb_v4.1.13:${CICD_EXECUTION_SEQUENCE}
      registry: 10.0.8.61:31484
    env:
      PLUGIN_DEBUG: "true"
      PLUGIN_INSECURE: "true"
      PLUGIN_STORAGE_PATH: /var/lib/docker2
- name: deploy
  steps:
  - applyYamlConfig:
      path: ./mongo_service.yml
  - applyYamlConfig:
      path: ./mongo-statefulset.yaml
timeout: 600
notification: {}
