---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: mongotesting
spec:
  serviceName: "mongotesting"
  replicas: 3
  template:
    metadata:
      labels:
        role: mongotesting
        environment: test
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongotesting
          image: csp2-centos-1:5000/fiware-mongo
          resources:
            limits:
             memory: "1Gi"
             cpu: "1000m"
            requests:
             memory: "500Mi"
             cpu: "500m"
          command:
            - mongod
            - "--replSet"
            - rs3
            - "--bind_ip"
            - 0.0.0.0
          ports:
            - containerPort: 27017
          readinessProbe:
           exec :
             command:
             - bash
             - "-c"          
             - |
               set -ex  
               mongo --eval "rs.initiate({_id: 'rs3',members: [{_id: 0, host: 'mongo-0.mongo.fiware.svc.cluster.local:27017'},{_id: 1, host: 'mongo-1.mongo.updateandrollback.svc.cluster.local:27017'},{_id: 2, host: 'mongo-2.mongo.fiware.svc.cluster.local:27017'}]})";
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
        - name: mongo-sidecar
          image: csp2-centos-1:5000/fiware-mongo-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "role=mongo,environment=test"
  volumeClaimTemplates:
  - metadata:
      name: mongo-storage
    spec:
      storageClassName: standard
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi